package com.miaoshasha.base.mapper.store;


import com.miaoshasha.common.entity.store.StoreDetail;

public interface StoreDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_store_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_store_detail
     *
     * @mbg.generated
     */
    int insert(StoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_store_detail
     *
     * @mbg.generated
     */
    int insertSelective(StoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_store_detail
     *
     * @mbg.generated
     */
    StoreDetail selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_store_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_store_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(StoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_store_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StoreDetail record);
}