package com.miaoshasha.base.mapper.product;

import com.miaoshasha.common.entity.product.BrandInfo;

public interface BrandInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_info
     *
     * @mbg.generated
     */
    int insert(BrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_info
     *
     * @mbg.generated
     */
    int insertSelective(BrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_info
     *
     * @mbg.generated
     */
    BrandInfo selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BrandInfo record);
}