package com.miaoshasha.base.mapper.product;

import com.miaoshasha.common.entity.product.ProductAttrItem;

public interface ProductAttrItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_item
     *
     * @mbg.generated
     */
    int insert(ProductAttrItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_item
     *
     * @mbg.generated
     */
    int insertSelective(ProductAttrItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_item
     *
     * @mbg.generated
     */
    ProductAttrItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductAttrItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductAttrItem record);
}