package com.miaoshasha.base.mapper.product;

import com.miaoshasha.common.entity.product.ProductAttrRel;

public interface ProductAttrRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_rel
     *
     * @mbg.generated
     */
    int insert(ProductAttrRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_rel
     *
     * @mbg.generated
     */
    int insertSelective(ProductAttrRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_rel
     *
     * @mbg.generated
     */
    ProductAttrRel selectByPrimaryKey(Long pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductAttrRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductAttrRel record);
}