package com.miaoshasha.common.entity.product;

import com.miaoshasha.common.base.AbstractBaseEntity;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_attr
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class ProductAttr extends AbstractBaseEntity{
    /** */
    private Long attrId;

    /** 属性名称*/
    private String attrName;

    /** */
    private Long categoryId;

    /** 是否搜索属性,0-否，1-是*/
    private Boolean isSearch;

    /** 是否必填,0-否，1-必填*/
    private Boolean isRequired;

    /** 属性类型，1-多选，2-单选，3-输入，4-下拉列表，5-颜色选项,6-时间选项*/
    private Integer attrType;

    /** 是否销售属性，展现到销售选择页上*/
    private Boolean isSale;

    /** 状态*/
    private Integer state;

    /** 排序*/
    private Integer seqNo;

    /** 备注*/
    private String notes;


    @Override
    public Long getId() {
        return this.attrId;
    }
}