package com.miaoshasha.common.entity.product;

import com.miaoshasha.common.base.AbstractBaseEntity;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class ProductInfo  extends AbstractBaseEntity {
    /** 主键*/
    private Long productId;

    /** 产品编码*/
    private String productCode;

    /** 商品名称*/
    private String productName;

    /** 商品副名称，记录一些促销信息等*/
    private String productSubname;

    /** 商品大类*/
    private Long categoryId;

    /** 产品图标*/
    private String productIcon;

    /** 品牌名称*/
    private Long brandId;

    /** 单位*/
    private String unit;

    /** 关键词，多个用英文分号隔开，不超过10个*/
    private String tags;

    /** 归属类型，1-通用，2-归属到商户*/
    private Long belongType;

    /** 归属商户*/
    private Long belongCust;

    /** 商品状态，10-草稿，20-提交审核，30-已发布，40-审核不通过*/
    private Integer state;


    @Override
    public Long getId() {
        return this.productId;
    }
}