package com.miaoshasha.common.entity.system;

import com.miaoshasha.common.base.AbstractBaseEntity;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_dict
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Dict extends AbstractBaseEntity {
    /** */
    private Long dictId;

    /** 字典编码*/
    private String dictCode;

    /** 字典名称*/
    private String dictName;

    /** 状态*/
    private Integer state;

    /** 备注*/
    private String notes;


    @Override
    public Long getId() {
        return this.dictId;
    }
}